### ISSUE TITLE
Uncaught SyntaxError when series name contains apostrophe

### ISSUE THREAD

**Issue by andydevlinsmith** [roughsmoothengine/organize-series#49]
I noticed this error when the plugin is displaying a series with an apostrophe in the title:
Uncaught SyntaxError: Unexpected identifier
post.php?post=82399&action=edit:2072 

The error seems to occur when displaying the os_defaultSettings['series_post_list_box'] options. In our case there was a series named "Use the organization's email domain name" - and this seemed to break the display.

**Comment by nerrad** [comment]
Moving this to the Organize Series Shortcodes repository issues tracker (https://gitlab.com/organize-series/organize-series-shortcodes/issues/8)
