### ISSUE TITLE
Method for Handling Unwritten Future Posts

### ISSUE THREAD

**Issue by EnigmaSolved** [roughsmoothengine/organize-series#5]
Hi Darren,

I am a long time fan of your Organize Series plugin.  I recall from forum threads in years past that there is interest in, and certain technical challenges to implementing, a feature for somehow indicating unpublished future posts in the list of items in a given series.  I believe part of the difficulty (if I recall correctly) is that there's not been any way within WordPress to get data on "potential" (ie, unpublished) posts in the way that is needed to actually display their info as upcoming posts in a given series.

Although (after composing most of this Issue) I did just come across an old forum post ( https://wordpress.org/support/topic/future-posts-and-drafts ) where you indicated:

> You should be able to accomplish this functionality via the Organize Series Extra Tokens addon (available at organizeseries.com). We added some extra tokens and a extra series template for displaying unpublished posts in series to users.

I had previously checked your site regarding this ( http://organizeseries.com/2010/os-extra-tokens-faq/ ), but now I do see mention of something in the Changelog ( http://organizeseries.com/2010/extra-tokens-changelog/ ) which supports the above forum post (but which I'd previously missed). 

So my below ideas may be redundant now, but since I took the time to write it all out and think through the logic, etc. I'm going to go ahead and post it and you can let me know if the Extra Tokens functionality already accomplishes this (or how it differs if not). :)

So here's my idea for a workaround (to what I perceived to be a problem with displaying info about unpublished or unwritten posts) that I think should be comparatively doable to implement, and which could achieve the spirit of what folks (such as myself) are wanting.  There's a couple of versions to this, so I'll start with the simplest and then expand on that.

1) For `Series Details`, add a field for `Planned Total Number of Posts in Series`. This value (if set) would then give us a number to work with while the number of posts in the series is less than that number (if the number of actual posts exceeds the defined number then obviously the defined number should be ignored).  Now we can add a new template in `Series Options` (perhaps called `Series Post List Future Posts Template`) which can make use of some new Tokens (perhaps called `%total_posts_in_series_planned%` and `%unpublished_posts_in_series_planned%`), allowing us to create content like the following: `There are 4 more posts in this series forthcoming.`  Which in the Template text box would look like: `There are %unpublished_posts_in_series_planned% more posts in this series forthcoming.`

So then if the user defines a `Planned Total Number of Posts in Series` for a given series, then you can output one more `<li>` (for the `Series Post List Template` content) which would generate the content of the `Series Post List Future Posts Template` within that `<li>`, rendering something like this:

```
1. Hello world!
2. Hello universe!
3. There are 2 more posts in this series forthcoming.
```

Similarly, it'd be good to have a `Series Meta Future Posts Template` and an accompanying `%series_meta_future_posts%` Token (which would output the `Series Meta Future Posts Template` content for use within the regular `Series Meta` Template box), since users may wish to word things differently for the `Series Meta`.

2) Now, if you wanted to go further (which I certainly would not object to) you could do a few more things to make this even better. We could add another Template along the lines of `Series Post List Skipped Number Template`, which might default to something like this:
`<li class="serieslist-li-skip">&hellip;</li>`

Then the user can add CSS to their style sheet of:
`.serieslist-li-skip{ list-style: none; }`

In conjunction with this, the final `<li>` (which outputs the defined sentence about future, unpublished posts in the series) can use the `value` attribute (of the `<li>`) in order to change the number displayed for that line (where value would be set to the defined future planned posts number). The resulting html for that line would look something like this:
`<li class="serieslist-li" value="4">There are 2 more posts in this series forthcoming.</li>`

And the whole thing together would look like:

```
1. Hello world!
2. Hello universe!
   ...
4. There are 2 more posts in this series forthcoming.
```

And that's definitely my favorite of the two options. :)

Regardless of whether you decide the above is worthwhile (and whether or not it is duplicating existing functionality), it would recommend that you could further explain (here, if not on your site) what exactly the additions to your Extra Tokens addon do (as I'm definitely fuzzy on those details, and I'm probably not alone in that). And if it turns out the above ideas would actually be useful additions I'd be open to potentially contributing some code via pull requests. :)

Thanks!
Sean

**Comment by nerrad** [comment]
Hey Sean,

Great outline.  You are correct the `Organize Series Extra Tokens` plugin adds some extra code for showing unpublished posts.  Two extra tokens for the templates in Organize Series Settings:

`%unpublished_post_title%`
`%total_posts_in_series_with_unpub%`

Extra tokens also adds an extra field to the templates for controlling how the unpublished post title appears in the list.

So basically users's would get an output with something like this:

```
Some Awesome Series

1. The Beginning of the Series
2. The Middle of the Series.
3. _Near the end of the Series._
4. _The End of the Series._
```

The last two items in that list in my example represent unpublished posts, user's could style them however they want (or even choose to not display them if they don't want).

So those new additions in that add-on take care of much of what you were suggesting (and people can choose to just disable the output of unpublished info by keeping the relevant field blank and not using the extra tokens.

What this work does _not_ do (from your list) of suggestions is customize the navigation.  Also, this functionality is dependent on series authors still creating the total number of posts for the series ahead of time and leaving the unfinished as unpublished/draft. Which also means, that each _unpublished_ post title is listed vs your idea of having one line item display how many more posts in the series are coming.

I certainly welcome pull requests, however in this case I probably won't merge in any to Organize Series core  because its functionality that is currently part of the extra tokens add-on.  Any further development of easier template display for unpublished posts etc would probably go in that add-on.

**Comment by EnigmaSolved** [comment]
Hey Darren,

Thanks much for those details--much appreciated! When I have a chance I think I'll start with purchasing the add-on and see how that works for me. And I agree it would make sense for my proposed additions to be folded into that add-on, as opposed to core.

Do you know if the current functionality (you describe above) works in those ways if the additional posts are *scheduled*, future posts (as opposed to just *unpublished* or *draft*)?

**Comment by nerrad** [comment]
> Do you know if the current functionality (you describe above) works in those ways if the additional posts are scheduled, future posts (as opposed to just unpublished or draft)?

It works as described for any post status that is not `published` or `private`.  So yes it should work for future (scheduled) posts as well.

**Comment by nerrad** [comment]
Closing this ticket for now.  Great ideas but not something that would be implemented in the core plugin and the current extra tokens add-on gets things part way there.
