### ISSUE TITLE
Fix problem with series-meta not showing correctly as expected with post-content (for excerpts)

### ISSUE THREAD

**Issue by nerrad** [roughsmoothengine/organize-series#53]
See the original report and the thread in the [wordpress.org support thread](https://wordpress.org/support/topic/series-meta-not-shows/)

There is a mismatch with removing filters (using the correct priority) as noted in the above thread.

**Comment by jtbayly** [comment]
Thanks. I originally said that the proposed fix in the comments works, but it doesn't work completely right. It does display the meta on the post, but then it also displays it on the excerpt, which is obviously not right. Just thought I'd add that.

**Comment by nerrad** [comment]
Thanks for updating with that info.  I'll do my own tests once the fix is implemented before releasing :)
