### ISSUE TITLE
Conflict with Revive All Posts plugin

### ISSUE THREAD

**Issue by kindagmanu** [roughsmoothengine/organize-series#58]
A while back I have noticed that an error is occurring with Organize Series plugin when Revive Old Posts posts to Facebook and Twitter. Certain posts get a line of text from Organize series meta attached before the title, even though those posts are not part of the series.

Here are sample Facebook posts with this error:
https://facebook.com/spillwords/posts/892485667625960
https://facebook.com/spillwords/posts/892485734292620
https://facebook.com/spillwords/posts/890725781135282

I have contacted the support of Revive old posts and was told that the plugin only picks up the contents of the posts from the tables, and since the error line is variable they are unable to eliminate the error line.

Is it possible to move the meta line to be part of series post navigation template? I have tried to include the meta template into the navigational one but it looses the series count. Also if I move it below the post content it moves way below the author box at the bottom of the post and I would need it to be next to the series navigation. I would really appreciate your help in solving this issue.

Thank you

**Comment by nerrad** [comment]
Hi @kindagmanu, I'm happy to help troubleshoot conflicts with plugins for those who have paid for [Basic Support](https://organizeseries.com/downloads/support-license/) but generally I don't support those type of things here unless its very clear what is causing the conflict and it's something with a ready fix.  

So for now, I'm going to close this issue.  Sorry for the delay in getting back to you.
