### ISSUE TITLE
How can i move organize-series to after the content?

### ISSUE THREAD

**Issue by mimsalehi** [roughsmoothengine/organize-series#62]
Hi, I wanted to change the display of this plugin below posts (in other word, after the_content hook).
how can i do it?

**Comment by nerrad** [comment]
Hi @mimsalehi, sorry for the delay in replying.  This github repository is for reporting bugs, requesting features and making code contributions to Organize Series.  Support type questions are not answered here.  You can see if your answer is found in the [help documentation](https://docs.organizeseries.com) or you can purchase a [basic support license](https://organizeseries.com/downloads/support-license/) which gives you access to email support.
