### ISSUE TITLE
Inline editiing set all posts to "No serie"

### ISSUE THREAD

**Issue by jej** [roughsmoothengine/organize-series#72]
Hi,
When using the inline editing (ie. quick edit on the posts list page), the serie choice is always "No serie" even if post in already part of a serie. If the modifications are saved, the post is unlinked from its serie.
I tried to understand the problem with no success... I guess it's somewhere in /js/inline-series.js

**Comment by jej** [comment]
Well, no so difficult to solve at the end...

**Comment by nerrad** [comment]
Thanks for the contribution!  I'll review/test this in a couple days and get it merged 👍
